package io.legacyfighter.cabs.driverfleet;

public enum DriverAttributeName {
    PENALTY_POINTS, NATIONALITY, YEARS_OF_EXPERIENCE, MEDICAL_EXAMINATION_EXPIRATION_DATE, MEDICAL_EXAMINATION_REMARKS, EMAIL, BIRTHPLACE, COMPANY_NAME
}
